package three;

typedef WebGLProgramParameters = {
	var shaderID : String;
	var shaderType : String;
	var shaderName : String;
	var vertexShader : String;
	var fragmentShader : String;
	var defines : Null<haxe.DynamicAccess<ts.AnyOf3<String, Float, Bool>>>;
	var customVertexShaderID : Null<String>;
	var customFragmentShaderID : Null<String>;
	var isRawShaderMaterial : Bool;
	var glslVersion : Null<GLSLVersion>;
	var precision : String;
	var batching : Bool;
	var instancing : Bool;
	var instancingColor : Bool;
	var instancingMorph : Bool;
	var supportsVertexTextures : Bool;
	var outputColorSpace : ColorSpace;
	var alphaToCoverage : Bool;
	var map : Bool;
	var matcap : Bool;
	var envMap : Bool;
	var envMapMode : ts.AnyOf2<Bool, Int>;
	var envMapCubeUVHeight : Null<Float>;
	var aoMap : Bool;
	var lightMap : Bool;
	var bumpMap : Bool;
	var normalMap : Bool;
	var displacementMap : Bool;
	var emissiveMap : Bool;
	var normalMapObjectSpace : Bool;
	var normalMapTangentSpace : Bool;
	var metalnessMap : Bool;
	var roughnessMap : Bool;
	var anisotropy : Bool;
	var anisotropyMap : Bool;
	var clearcoat : Bool;
	var clearcoatMap : Bool;
	var clearcoatNormalMap : Bool;
	var clearcoatRoughnessMap : Bool;
	var iridescence : Bool;
	var iridescenceMap : Bool;
	var iridescenceThicknessMap : Bool;
	var sheen : Bool;
	var sheenColorMap : Bool;
	var sheenRoughnessMap : Bool;
	var specularMap : Bool;
	var specularColorMap : Bool;
	var specularIntensityMap : Bool;
	var transmission : Bool;
	var transmissionMap : Bool;
	var thicknessMap : Bool;
	var gradientMap : Bool;
	var opaque : Bool;
	var alphaMap : Bool;
	var alphaTest : Bool;
	var alphaHash : Bool;
	var combine : Null<Side>;
	var mapUv : ts.AnyOf2<String, Bool>;
	var aoMapUv : ts.AnyOf2<String, Bool>;
	var lightMapUv : ts.AnyOf2<String, Bool>;
	var bumpMapUv : ts.AnyOf2<String, Bool>;
	var normalMapUv : ts.AnyOf2<String, Bool>;
	var displacementMapUv : ts.AnyOf2<String, Bool>;
	var emissiveMapUv : ts.AnyOf2<String, Bool>;
	var metalnessMapUv : ts.AnyOf2<String, Bool>;
	var roughnessMapUv : ts.AnyOf2<String, Bool>;
	var anisotropyMapUv : ts.AnyOf2<String, Bool>;
	var clearcoatMapUv : ts.AnyOf2<String, Bool>;
	var clearcoatNormalMapUv : ts.AnyOf2<String, Bool>;
	var clearcoatRoughnessMapUv : ts.AnyOf2<String, Bool>;
	var iridescenceMapUv : ts.AnyOf2<String, Bool>;
	var iridescenceThicknessMapUv : ts.AnyOf2<String, Bool>;
	var sheenColorMapUv : ts.AnyOf2<String, Bool>;
	var sheenRoughnessMapUv : ts.AnyOf2<String, Bool>;
	var specularMapUv : ts.AnyOf2<String, Bool>;
	var specularColorMapUv : ts.AnyOf2<String, Bool>;
	var specularIntensityMapUv : ts.AnyOf2<String, Bool>;
	var transmissionMapUv : ts.AnyOf2<String, Bool>;
	var thicknessMapUv : ts.AnyOf2<String, Bool>;
	var alphaMapUv : ts.AnyOf2<String, Bool>;
	var vertexTangents : Bool;
	var vertexColors : Bool;
	var vertexAlphas : Bool;
	var vertexUv1s : Bool;
	var vertexUv2s : Bool;
	var vertexUv3s : Bool;
	var pointsUvs : Bool;
	var fog : Bool;
	var useFog : Bool;
	var fogExp2 : Bool;
	var flatShading : Bool;
	var sizeAttenuation : Bool;
	var logarithmicDepthBuffer : Bool;
	var skinning : Bool;
	var morphTargets : Bool;
	var morphNormals : Bool;
	var morphColors : Bool;
	var morphTargetsCount : Float;
	var morphTextureStride : Float;
	var numDirLights : Float;
	var numPointLights : Float;
	var numSpotLights : Float;
	var numSpotLightMaps : Float;
	var numRectAreaLights : Float;
	var numHemiLights : Float;
	var numDirLightShadows : Float;
	var numPointLightShadows : Float;
	var numSpotLightShadows : Float;
	var numSpotLightShadowsWithMaps : Float;
	var numLightProbes : Float;
	var numClippingPlanes : Float;
	var numClipIntersection : Float;
	var dithering : Bool;
	var shadowMapEnabled : Bool;
	var shadowMapType : CullFace;
	var toneMapping : DepthModes;
	var useLegacyLights : Bool;
	var decodeVideoTexture : Bool;
	var premultipliedAlpha : Bool;
	var doubleSided : Bool;
	var flipSided : Bool;
	var useDepthPacking : Bool;
	var depthPacking : Int;
	var index0AttributeName : Null<String>;
	var extensionClipCullDistance : Bool;
	var extensionMultiDraw : Bool;
	var rendererExtensionParallelShaderCompile : Bool;
	var customProgramCacheKey : String;
};